cqfd: add new ini parser
The .ini parser is implemented using a series of bash substitutions that
transform an .ini-style configuration file into shell instructions. The
original code was written by Andrés J. Díaz and later improved and
simplified.

In practice, sections are converted into functions whose names are
prefixed with cfg_section_, while properties are translated into
variables. The resulting code is then evaluated with eval, and the
section functions are executed to set the corresponding properties in
the shell environment.

That bash-substitutions based parser assumes lines are shell variables,
and thus, they are **NOT** commands. This assumption is incorrect and
dangerous.

The following .cqfdrc will destroy your world, **DO NOT TRY IT!**:

	[project]
	org="savoirfairelinux"
	name="cqfd"
	echo "Good Bye, World!"

	[build]
	command="/bin/echo" rm -Rf / 2>&1
	files=TO-LET-FUNCTION-RETURN-0

This configuration produces the following shell code:

	function cfg_section_project {
		org="savoirfairelinux"
		name="cqfd"
		echo "Good Bye, World!"
	}

	function cfg_section_build {
		command="/bin/echo" rm -Rf / 2>&1
		files=TO-LET-FUNCTION-RETURN-0
	}

When cqfd calls cfg_section_project(), it prints “Good Bye, World!” to
stdout. When it calls cfg_section_build(), it starts removing files from
the root directory until interrupted.

	$ cqfd
	Good Bye, World!
	rm: cannot remove '/usr/bin/[': Permission denied
	rm: cannot remove '/usr/bin/addpart': Permission denied
	rm: cannot remove '/usr/bin/apt': Permission denied
	rm: cannot remove '/usr/bin/apt-cache': Permission denied
	rm: cannot remove '/usr/bin/apt-cdrom': Permission denied
	rm: cannot remove '/usr/bin/apt-config': Permission denied
	rm: cannot remove '/usr/bin/apt-get': Permission denied
	rm: cannot remove '/usr/bin/apt-key': Permission denied
	rm: cannot remove '/usr/bin/apt-mark': Permission denied
	^C

While the echo command is easy to spot, the second command is far more
subtle and dangerous.

This issue is well known [1][2][3][4] and cannot be safely fixed in the
current approach.

This change introduces a completely new .ini parser that treats
configuration files as data and prevents command evaluation.

[1]: https://ajdiaz.wordpress.com/2008/02/09/bash-ini-parser/#comment-454
[2]: https://ajdiaz.wordpress.com/2008/02/09/bash-ini-parser/#comment-455
[3]: https://ajdiaz.wordpress.com/2008/02/09/bash-ini-parser/#comment-457
[4]: https://ajdiaz.wordpress.com/2008/02/09/bash-ini-parser/#comment-458

diff --git a/cqfd b/cqfd
--- a/cqfd
+++ b/cqfd
@@ -104,33 +104,6 @@ Command options for --run:
 EOF
 }
 
-## cfg_parser() - parse ini-style config files
-# Will parse a ini-style config file, and evaluate it to a bash array.
-#   Ref: https://ajdiaz.wordpress.com/2008/02/09/bash-ini-parser/
-#        by Andrés J. Díaz - License: MIT
-# $1: path to ini file
-cfg_parser() {
-	local ini
-
-	mapfile -t ini <"$1"                                 # convert to line-array
-	ini=("${ini[@]//[/\\[}")                             # escape [
-	ini=("${ini[@]//]/\\]}")                             # escape ]
-	# Remove comments with ; tabs, and spaces up to cqfd6 (not included)
-	if [ "$COMPAT" -lt 6 ]; then
-		ini=("${ini[@]//;*/}")                       # remove comments with ;
-		ini=("${ini[@]/$'\t'=/=}")                   # remove tabs before =
-		ini=("${ini[@]/=$'\t'/=}")                   # remove tabs after =
-		ini=("${ini[@]/\ =/=}")                      # remove space before =
-		ini=("${ini[@]/=\ /=}")                      # remove space after =
-	fi
-	ini=("${ini[@]/#\\[/$'\n}\nfunction cfg_section_'}") # convert section to function (1)
-	ini=("${ini[@]/%\\]/ { :}")                          # convert section to function (2)
-	ini+=("}")                                           # add the last brace
-	ini[0]="${ini[0]/\}/}"                               # remove the first brace
-	ini=("$(printf "%s\n" "${ini[@]}")")                 # reconvert to line-array
-	eval "${ini[*]}"                                     # eval the result
-}
-
 ## warn() - output warning
 # $*: messages and variables shown in the message
 warn() {
@@ -244,6 +217,92 @@ docker_images() {
 			fi
 
 			echo "$image" "$status" "$dockerfile" "dockerfile_hash" "$hash"
+		done
+	done
+}
+
+## source_ini_file() - source ini file to INI* bash arrays
+# $1: path to ini file
+source_ini_file() {
+	local multiline
+	local section
+	local line
+
+	# Unset former context
+	unset INI "${!INI@}"
+
+	# Convert lines to bash array and iterate over lines
+	mapfile -t lines <"$1"
+	for line in "${lines[@]}"; do
+		# Prepend previous multiline if any
+		if [[ "$multiline" ]]; then
+			line="$multiline
+$line"
+			unset multiline
+		fi
+
+		# Skip shell and .ini comments
+		if [[ "$line" =~ ^[\ \	]*[\#\;] ]]; then
+			continue
+		# Save multiline and continue
+		elif [[ "$line" =~ \\$ ]]; then
+			multiline="$line"
+			continue
+		fi
+
+		# Add new section
+		if [[ "$line" =~ ^\[(.*)\]$ ]]; then
+			section="${BASH_REMATCH[1]}"
+			section="${section//./_}"
+			section="${section//-/_}"
+			eval "INI+=('${BASH_REMATCH[1]}')"
+			eval "INI__${section^^}=()"
+		# Add new property to current section
+		elif [[ "$line" =~ ^([A-Za-z0-9_-]+)[\ \	]*(\+?=)[\ \	]*(.*)$ ]]; then
+			local property
+			local value
+			property="${BASH_REMATCH[1]}"
+			property="${property//./_}"
+			property="${property//-/_}"
+			value="${BASH_REMATCH[3]}"
+			eval "INI__${section^^}__${property^^}${BASH_REMATCH[2]}$value"
+			eval "INI__${section^^}+=('${BASH_REMATCH[1]}')"
+		# Return
+		elif [[ "$line" ]]; then
+			warn "line \"$line\" is invalid"
+			return 1
+		fi
+	done
+}
+
+## source_ini_sections() - source sections to environment
+# $*: sections from the ini file to source
+source_ini_sections() {
+	local section
+	local ini
+
+	for section in "$@"; do
+		local ini
+		for ini in "${INI[@]}"; do
+			if [ "$ini" = "$section" ]; then
+				break
+			fi
+		done
+		if [ "$ini" != "$section" ]; then
+			return 1
+		fi
+
+		local sections
+		eval "sections=(\"\${INI__${section^^}[@]}\")"
+		if [[ "${#sections[@]}" -eq 0 ]]; then
+			return
+		fi
+
+		local property
+		local properties
+		eval "properties=(\"\${INI__${section^^}[@]}\")"
+		for property in "${properties[@]}"; do
+			eval "$property=\"\${INI__${section^^}__${property^^}}\""
 		done
 	done
 }
@@ -857,7 +916,7 @@ load_config() {
 	fi
 
 	# parse cqfdrc file
-	if ! cfg_parser "$cqfdrc"; then
+	if ! source_ini_file "$cqfdrc"; then
 		die ".cqfdrc: Invalid ini-file!"
 	fi
 
@@ -895,13 +954,10 @@ load_config() {
 		platform="$native"
 	fi
 
-	# generate dynamically the list of flavors based on the names of shell
-	# functions reported by the builtin:
-	#  - the cfg_section_ prefix is stripped
-	#  - the build and project sections are stripped
+	# generate dynamically the list of flavors based on the sections (build
+	# and project sections are stripped out
 	local flavors
-	mapfile -t flavors < <(compgen -A function -X '!cfg_section_*')
-	flavors=("${flavors[@]/cfg_section_/}")
+	flavors=("${INI[@]}")
 	local i
 	for i in "${!flavors[@]}"; do
 		if [[ "${flavors[$i]}" =~ ^(build|project)$ ]]; then
@@ -912,7 +968,7 @@ load_config() {
 	flavors="${flavors[*]}"
 
 	# load the [project] section
-	if ! cfg_section_project 2>/dev/null; then
+	if ! source_ini_sections project; then
 		die ".cqfdrc: Missing project section!"
 	fi
 
@@ -937,17 +993,15 @@ load_config() {
 	fi
 
 	# load the [build] section
-	if ! cfg_section_build 2>/dev/null; then
+	if ! source_ini_sections build; then
 		die ".cqfdrc: Missing build section!"
 	fi
 
 	# build parameters may be overriden by a flavor defined in the
 	# build section's 'flavors' parameter.
-	local flavor="$1"
-	if [ -n "$flavor" ]; then
-		# load the [$flavor] section
-		if ! cfg_section_"$flavor" 2>/dev/null; then
-			die ".cqfdrc: Missing $flavor section!"
+	if [ -n "$1" ]; then
+		if ! source_ini_sections "$1" 2>/dev/null; then
+			die ".cqfdrc: Missing $1 section!"
 		fi
 	fi
 
