Revert "cqfd: exec, shell: allows to release"
This reverts commit 34362fd872a829258e8f1062ea99b5b5392b0718.

diff --git a/cqfd b/cqfd
--- a/cqfd
+++ b/cqfd
@@ -936,9 +936,7 @@ load_config() {
 }
 
 has_to_release=false
-if [ "$#" -eq 0 ]; then
-	load_config
-fi
+has_alternate_command=false
 while [ $# -gt 0 ]; do
 	case "$1" in
 	help|-h|--help)
@@ -1012,8 +1010,9 @@ while [ $# -gt 0 ]; do
 			die "exec: Missing arguments!"
 		fi
 		load_config "$flavor"
-		build_command="${*@Q}"
-		break
+		command_string="${*@Q}"
+		docker_run "$command_string"
+		exit
 		;;
 	run|release)
 		if [ "$1" = "release" ]; then
@@ -1021,8 +1020,6 @@ while [ $# -gt 0 ]; do
 		fi
 
 		shift
-
-		load_config "$flavor"
 
 		# No more args? run default command
 		[ "$#" -eq 0 ] && break
@@ -1035,17 +1032,11 @@ while [ $# -gt 0 ]; do
 				usage
 				die "run -c: Missing arguments!"
 			fi
-
-			if [ -z "$build_command" ]; then
-				warn ".cqfdrc: Missing or empty build.command property!"
-			fi
-
-			build_command+=" $*"
 			break
 		fi
 
 		# Run alternate command
-		build_command="$*"
+		has_alternate_command=true
 		break
 		;;
 	sh|ash|dash|bash|ksh|zsh|csh|tcsh|fish|shell)
@@ -1054,11 +1045,12 @@ while [ $# -gt 0 ]; do
 		fi
 		shift
 		load_config "$flavor"
-		build_command="$cqfd_shell"
+		command_string="$cqfd_shell"
 		if [ "$#" -gt 0 ]; then
-			build_command+=" ${*@Q}"
+			command_string+=" ${*@Q}"
 		fi
-		break
+		docker_run "$command_string"
+		exit
 		;;
 	*)
 		usage
@@ -1067,6 +1059,18 @@ while [ $# -gt 0 ]; do
 	esac
 	shift
 done
+
+load_config "$flavor"
+
+if ! $has_alternate_command && [ -n "$*" ] && [ -z "$build_command" ]; then
+	warn ".cqfdrc: Missing or empty build.command property!"
+fi
+
+if $has_alternate_command; then
+	build_command="$*"
+elif [ -n "$*" ]; then
+	build_command+=" $*"
+fi
 
 if [ -z "$build_command" ]; then
 	die ".cqfdrc: Missing or empty build.command property!"
