cqfd: standardize die messages
This rewords some die message in the format: "topic: message!".

diff --git a/cqfd b/cqfd
--- a/cqfd
+++ b/cqfd
@@ -348,12 +348,12 @@ make_archive() {
 
 	eval "files=($release_files)"
 	if [ -z "${files[*]}" ]; then
-		die "No files to archive, check files in $cqfdrc"
+		die "$cqfdrc: Missing or empty build.files property!"
 	fi
 
 	for file in "${files[@]}"; do
 		if [ ! -e "$file" ]; then
-			die "Unable to release: unable to find $file"
+			die "$file: Missing file!"
 		fi
 	done
 
@@ -530,7 +530,7 @@ locate_project_dir() {
 # $1: optional "flavor" of the build, is a suffix of command
 load_config() {
 	if ! cqfd_project_dir=$(locate_project_dir); then
-		die ".cqfd directory not found in directory tree"
+		die ".cqfd: Missing project directory!"
 	fi
 
 	# unless using '-f other_cqfdrc', use base directory located above
@@ -539,7 +539,7 @@ load_config() {
 	fi
 
 	if [ ! -f "$cqfdrc_dir$cqfdrc" ]; then
-		die "Unable to find $cqfdrc_dir$cqfdrc - create it or pick one using 'cqfd -f'"
+		die "$cqfdrc_dir$cqfdrc: Missing project file!"
 	fi
 
 	if ! cfg_parser "$cqfdrc_dir$cqfdrc"; then
@@ -560,7 +560,7 @@ load_config() {
 
 	# load the [project] section
 	if ! cfg_section_project 2>/dev/null; then
-		die "$cqfdrc: Missing project section!"
+		die "$cqfd_dir$cqfdrc: Missing project section!"
 	fi
 
 	# shellcheck disable=SC2154
@@ -574,12 +574,12 @@ load_config() {
 
 	# check for [project] org and name properties are set and are not empty
 	if [ -z "$project_org" ] || [ -z "$project_name" ]; then
-		die "$cqfdrc: Missing project.org or project.name properties"
+		die "$cqfd_dircqfdrc: Missing project.org or project.name properties!"
 	fi
 
 	# load the [build] section
 	if ! cfg_section_build 2>/dev/null; then
-		die "$cqfdrc: Missing build section!"
+		die "$cqfd_dircqfdrc: Missing build section!"
 	fi
 
 	build_flavors="${flavors[*]}"
@@ -588,13 +588,9 @@ load_config() {
 	# build section's 'flavors' parameter.
 	local flavor="$1"
 	if [ -n "$flavor" ]; then
-		if grep -qw "$flavor" <<< "${flavors[*]}"; then
-			# load the [$flavor] section
-			if ! cfg_section_"$flavor" 2>/dev/null; then
-				die "$cqfdrc: Missing $flavor section!"
-			fi
-		else
-			die "flavor \"$flavor\" not found in flavors list"
+		# load the [$flavor] section
+		if ! cfg_section_"$flavor" 2>/dev/null; then
+			die "$cqfd_dir$cqfdrc: Missing $flavor section!"
 		fi
 	fi
 
@@ -619,7 +615,7 @@ load_config() {
 
 	dockerfile="$cqfd_project_dir/$cqfddir/${build_distro:-docker}/Dockerfile"
 	if [ ! -f "$dockerfile" ]; then
-		die "$dockerfile not found"
+		die "$dockerfile: Missing Dockerfile!"
 	fi
 
 	if [ "$project_custom_img_name" ]; then
@@ -737,7 +733,7 @@ while [ $# -gt 0 ]; do
 		;;
 	*)
 		usage
-		die "$1: Invalid command"
+		die "$1: Invalid command!"
 		;;
 	esac
 	shift
@@ -746,7 +742,7 @@ done
 load_config "$flavor"
 
 if ! $has_alternate_command && [ -n "$*" ] && [ -z "$build_command" ]; then
-	warn "$cqfdrc: Missing or empty build.command property"
+	warn "$cqfdrc: Missing or empty build.command property!"
 fi
 
 if $has_alternate_command; then
@@ -756,7 +752,7 @@ elif [ -n "$*" ]; then
 fi
 
 if [ -z "$build_command" ]; then
-	die "$cqfdrc: Missing or empty build.command property"
+	die "$cqfdrc: Missing or empty build.command property!"
 fi
 
 docker_run "$build_command"
