*** :{) ***

diff --git a/cqfd b/cqfd
--- a/cqfd
+++ b/cqfd
@@ -736,8 +736,12 @@ locate_project_dir() {
 load_config() {
 	# get the project directory
 	local project_dir
-	if ! project_dir=$(locate_project_dir); then
-		die ".cqfd: Missing project directory!"
+
+	project_dir="$PWD"
+	if [ ! "$CQFD_DIR" ]; then
+		if ! project_dir=$(locate_project_dir); then
+			die ".cqfd: Missing project directory!"
+		fi
 	fi
 
 	local workdir
diff --git a/tests/Makefile b/tests/Makefile
--- a/tests/Makefile
+++ b/tests/Makefile
@@ -19,7 +19,9 @@ tests:
 	@export CQFD_CACHE=$(TDIR); \
 	for f in [0-9][0-9]*; do \
 		if [ -x "$$f" ]; then \
-			./$$f $(TDIR); \
+			if bash -x $$f $(TDIR); then \
+				echo "$$f has errors" >&2; \
+			fi; \
 		fi; \
 	done; \
 	failed=0; \
