cqfd: uniformize command argument parsing
This uniformizes the argument parsing of every commands.

diff --git a/cqfd b/cqfd
--- a/cqfd
+++ b/cqfd
@@ -1024,20 +1024,26 @@ has_to_release=false
 while [ $# -gt 0 ]; do
 	case "$1" in
 	help|-h|--help)
-		if [ "$1" = help ] && [ "$#" -gt 1 ]; then
-			usage
-			die "help: Take no argument!"
-		fi
+		cqfd_command="$1"
 		shift
+
+		if [ "$cqfd_command" = help ] && [ "$#" -gt 0 ]; then
+			usage
+			die "$cqfd_command: Take no argument!"
+		fi
+
 		usage
 		exit
 		;;
 	version|-v|--version)
-		if [ "$1" = version ] && [ "$#" -gt 1 ]; then
-			usage
-			die "version: Take no argument!"
-		fi
+		cqfd_command="$1"
 		shift
+
+		if [ "$cqfd_command" = version ] && [ "$#" -gt 0 ]; then
+			usage
+			die "$cqfd_command: Take no argument!"
+		fi
+
 		echo "$VERSION"
 		exit
 		;;
@@ -1046,52 +1052,72 @@ while [ $# -gt 0 ]; do
 		export BUILDKIT_PROGRESS=plain
 		;;
 	init|--init)
+		cqfd_command="$1"
 		shift
+
 		if [ "$#" -gt 0 ]; then
 			usage
-			die "init: Take no argument!"
+			die "$cqfd_command: Take no argument!"
 		fi
+
 		load_config "$flavor"
+
 		docker_pull_or_build
 		exit
 		;;
 	deinit|--deinit)
+		cqfd_command="$1"
 		shift
+
 		if [ "$#" -gt 0 ]; then
 			usage
-			die "deinit: Take no argument!"
+			die "$cqfd_command: Take no argument!"
 		fi
+
 		load_config "$flavor"
+
 		docker_rmi
 		exit
 		;;
 	ls|--ls)
+		cqfd_command="$1"
 		shift
+
 		if [ "$#" -gt 0 ]; then
 			usage
-			die "ls: Take no argument!"
+			die "$cqfd_command: Take no argument!"
 		fi
+
 		load_config "$flavor"
+
 		list
 		exit
 		;;
 	gc|--gc)
+		cqfd_command="$1"
 		shift
+
 		if [ "$#" -gt 0 ]; then
 			usage
-			die "gc: Take no argument!"
+			die "$cqfd_command: Take no argument!"
 		fi
+
 		load_config "$flavor"
+
 		prune
 		exit
 		;;
 	flavors|--flavors)
+		cqfd_command="$1"
 		shift
+
 		if [ "$#" -gt 0 ]; then
 			usage
-			die "flavors: Too many arguments!"
+			die "$cqfd_command: Take no argument!"
 		fi
+
 		load_config
+
 		echo "$project_flavors"
 		exit
 		;;
@@ -1132,11 +1158,14 @@ while [ $# -gt 0 ]; do
 	exec|--exec)
 		cqfd_command="$1"
 		shift
+
 		if [ "$#" -lt 1 ]; then
 			usage
-			die "exec: Missing arguments!"
+			die "$cqfd_command: Missing arguments!"
 		fi
+
 		load_config "$flavor"
+
 		build_command="${*@Q}"
 		break
 		;;
@@ -1148,9 +1177,9 @@ while [ $# -gt 0 ]; do
 		if [ "$cqfd_command" = "release" ]; then
 			has_to_release=true
 			if [ "$#" -gt 0 ]; then
-				warn "command release shall not support argument(s)," \
+				warn "command $cqfd_command shall not support argument(s)," \
 				     "please consider the command --run instead:"
-				echo "               cqfd --release --run ${*@Q}" >&2
+				echo "               cqfd --$cqfd_command --run ${*@Q}" >&2
 			fi
 		fi
 
@@ -1168,7 +1197,7 @@ while [ $# -gt 0 ]; do
 
 			if [ "$#" -lt 1 ]; then
 				usage
-				die "run -c: Missing arguments!"
+				die "$cqfd_command -c: Missing arguments!"
 			fi
 
 			if [ -z "$build_command" ]; then
@@ -1200,11 +1229,14 @@ while [ $# -gt 0 ]; do
 		;;
 	shell|--shell)
 		cqfd_command="$1"
-		if [ "$1" != "shell" ] && [ "$1" != "--shell" ]; then
-			cqfd_shell="$1"
-		fi
 		shift
+
+		if [ "$1" = "shell" ] || [ "$1" = "--shell" ]; then
+			cqfd_shell="$cqfd_command"
+		fi
+
 		load_config "$flavor"
+
 		build_command="$cqfd_shell"
 		if [ "$#" -gt 0 ]; then
 			build_command+=" ${*@Q}"
@@ -1220,9 +1252,10 @@ while [ $# -gt 0 ]; do
 		die "$1: Invalid option!"
 		;;
 	*)
-		# Run command
-		cqfd_command="exec"
+		cqfd_command="$1"
+
 		load_config "$flavor"
+
 		build_command="${*@Q}"
 		break
 		;;
