cqfd: rename .cqfdrc to Cqfdfile
In interfactive shells, the *rc files are initialization files that are
read and executed at startup.

In cqfd, the .cqfdrc file is read and it is non stricly executed.

Thus, the .cqfdrc file is closer to a Dockerfile or a Makefile file than
a shell rc file.

This renames .cqfdrc file to Cqfdfile.

diff --git a/cqfd b/cqfd
--- a/cqfd
+++ b/cqfd
@@ -63,8 +63,8 @@ Options:
     --reinit             Reinitialize build container.
     --release            Release software.
     --platform <target>  Set target platform.
-    -f or --cqfdrc-file <file>
-                         Use file as config file (default .cqfdrc).
+    -f or --cqfd-file <file>
+                         Use file as config file (default Cqfdfile).
     -d or --cqfd-directory <directory>
                          Use directory as cqfd directory (default .cqfd).
     -w or --working-directory <directory>
@@ -92,7 +92,7 @@ Commands:
     --shell [shargs]     Run shell command inside build container.
 
     By default, the '--run' command is assumed, with the default
-    command string configured in your .cqfdrc (see build.command).
+    command string configured in your Cqfdfile (see build.command).
 
 Command options for --run:
     -c <argstring>       Append argument string to the default command string.
@@ -404,7 +404,7 @@ collect_images() {
 
 		echo "Removing images..."
 
-		# Append extra arguments from the .cqfdrc [build] section
+		# Append extra arguments from the Cqfdfile [build] section
 		if [ "$build_docker_rmi_args" ]; then
 			local array
 			# shellcheck disable=SC2162
@@ -467,7 +467,7 @@ docker_pull_or_build() {
 	# Pull the image
 	# If custom image name is used, it is pulled pull by docker_run()
 	if [ "$project_image" ] && [ ! "$project_custom_img_name" ] ; then
-		# Append extra arguments from the .cqfdrc [build] section
+		# Append extra arguments from the Cqfdfile [build] section
 		if [ "$build_docker_pull_args" ]; then
 			local array
 			# shellcheck disable=SC2162
@@ -490,7 +490,7 @@ docker_pull_or_build() {
 		return
 	fi
 
-	# Append extra arguments from the .cqfdrc [build] section
+	# Append extra arguments from the Cqfdfile [build] section
 	if [ "$build_docker_build_args" ]; then
 		local array
 		# shellcheck disable=SC2162
@@ -545,7 +545,7 @@ docker_rmi() {
 		die "$cqfd_image: Image busy!"
 	fi
 
-	# Append extra arguments from the .cqfdrc [build] section
+	# Append extra arguments from the Cqfdfile [build] section
 	if [ "$build_docker_rmi_args" ]; then
 		local array
 		# shellcheck disable=SC2162
@@ -600,7 +600,7 @@ docker_run() {
 		fi
 	fi
 
-	# Append extra arguments from the .cqfdrc [build] section
+	# Append extra arguments from the Cqfdfile [build] section
 	if [ "$build_docker_run_args" ]; then
 		local array
 		# shellcheck disable=SC2162
@@ -651,7 +651,7 @@ docker_run() {
 		    "CQFD_EXTRA_RUN_ARGS=\"-p <host_port>:<docker_port>\""
 	fi
 
-	# The user may set the user_extra_groups in the .cqfdrc
+	# The user may set the user_extra_groups in the Cqfdfile
 	# file to add groups to the user in the container.
 	if [ -n "$build_user_extra_groups" ]; then
 		local group
@@ -740,7 +740,7 @@ make_archive() {
 
 	eval "files=($release_files)"
 	if [ -z "${files[*]}" ]; then
-		die ".cqfdrc: Missing or empty build.files property!"
+		die "Cqfdfile: Missing or empty build.files property!"
 	fi
 
 	for file in "${files[@]}"; do
@@ -929,7 +929,7 @@ locate_project_dir() {
 	return 1
 }
 
-## load_config() - load build settings from cqfdrc
+## load_config() - load build settings from Cqfdfile
 # $1: optional "flavor" of the build, is a suffix of command
 load_config() {
 	# get the project directory
@@ -954,17 +954,29 @@ load_config() {
 		die ".cqfd: Missing or not a directory!"
 	fi
 
-	local cqfdrc
-	cqfdrc="${CQFDRC_FILE:-$project_dir/.cqfdrc}"
+	local cqfdfile
+	local file
+	for file in .cqfdrc Cqfdfile; do
+		cqfdfile="${CQFDFILE:-$project_dir/$file}"
+		# make an absolute path and check if it is a file
+		if [ -e "$cqfdfile" ]; then
+			break
+		fi
+	done
 	# make an absolute path and check if it is a file
-	if ! cqfdrc="$(realpath "$cqfdrc")" || \
-	   [ ! -f "$cqfdrc" ]; then
-		die ".cqfdrc: Missing or not a file!"
+	if ! cqfdfile="$(realpath "$cqfdfile")" || \
+		[ ! -f "$cqfdfile" ]; then
+		die "Cqfdfile: Missing or not a file!"
 	fi
 
-	# parse cqfdrc file
-	if ! source_ini_file "$cqfdrc"; then
-		die ".cqfdrc: Invalid ini-file!"
+	# warn if using legacy .cqfdrc
+	if [ "${cqfdfile##*/}" = .cqfdrc ]; then
+		warn ".cqfdrc is deprecated, rename it to Cqfdfile."
+	fi
+
+	# parse Cqfdfile file
+	if ! source_ini_file "$cqfdfile"; then
+		die "Cqfdfile: Invalid ini-file!"
 	fi
 
 	# deduce native platform from system
@@ -1016,7 +1028,7 @@ load_config() {
 
 	# load the [project] section
 	if ! source_ini_sections project; then
-		die ".cqfdrc: Missing project section!"
+		die "Cqfdfile: Missing project section!"
 	fi
 
 	# shellcheck disable=SC2154
@@ -1036,19 +1048,19 @@ load_config() {
 
 	# check for [project] org and name properties are set and are not empty
 	if [ -z "$project_org" ] || [ -z "$project_name" ]; then
-		die ".cqfdrc: Missing project.org or project.name properties!"
+		die "Cqfdfile: Missing project.org or project.name properties!"
 	fi
 
 	# load the [build] section
 	if ! source_ini_sections build; then
-		die ".cqfdrc: Missing build section!"
+		die "Cqfdfile: Missing build section!"
 	fi
 
 	# build parameters may be overriden by a flavor defined in the
 	# build section's 'flavors' parameter.
 	if [ -n "$1" ]; then
 		if ! source_ini_sections "$1" 2>/dev/null; then
-			die ".cqfdrc: Missing $1 section!"
+			die "Cqfdfile: Missing $1 section!"
 		fi
 	fi
 
@@ -1383,9 +1395,9 @@ while [ $# -gt 0 ]; do
 		shift
 		CQFD_DIR="$1"
 		;;
-	-f|--cqfdrc-file)
+	-f|--cqfd-file)
 		shift
-		CQFDRC_FILE="$1"
+		CQFDFILE="$1"
 		;;
 	-C|--directory)
 		shift
@@ -1457,7 +1469,7 @@ while [ $# -gt 0 ]; do
 		if [ "$#" -eq 0 ]; then
 			# Check for [build] command property is set and not empty
 			if [ -z "$build_command" ]; then
-				die ".cqfdrc: Missing or empty build.command property!"
+				die "Cqfdfile: Missing or empty build.command property!"
 			fi
 
 			# Run default command
@@ -1477,7 +1489,7 @@ while [ $# -gt 0 ]; do
 
 			# Check for [build] command property is set and not empty
 			if [ -z "$build_command" ]; then
-				warn ".cqfdrc: Missing or empty build.command property!"
+				warn "Cqfdfile: Missing or empty build.command property!"
 			fi
 
 			# Display a warning message if using -c with multiple arguments
@@ -1587,7 +1599,7 @@ if [ -z "$cqfd_command" ]; then
 
 	# Check for [build] command property is set and not empty
 	if [ -z "$build_command" ]; then
-		die ".cqfdrc: Missing or empty build.command property!"
+		die "Cqfdfile: Missing or empty build.command property!"
 	fi
 fi
 
