init

diff --git a/tests/00-setup b/tests/00-setup
--- a/tests/00-setup
+++ b/tests/00-setup
@@ -31,7 +31,7 @@ else
 fi
 
 ################################################################################
-# running 'cqfd init' should fail, as there's no proper config
+# running 'cqfd --init' should fail, as there's no proper config
 ################################################################################
 jtest_prepare "create a test skeleton in temporary directory"
 if ! "$cqfd" init; then
@@ -41,22 +41,22 @@ else
 fi
 
 ################################################################################
-# running 'cqfd init' should fail, as there's an empty config
+# running 'cqfd --init' should fail, as there's an empty config
 ################################################################################
-jtest_prepare "cqfd init complains with an empty .cqfdrc"
+jtest_prepare "cqfd --init complains with an empty .cqfdrc"
 touch "$TDIR/.cqfdrc"
-if ! "$cqfd" init; then
+if ! "$cqfd" --init; then
 	jtest_result pass
 else
 	jtest_result fail
 fi
 
 ################################################################################
-# running 'cqfd init' should fail, as there's an incomplete config
+# running 'cqfd --init' should fail, as there's an incomplete config
 ################################################################################
-jtest_prepare "cqfd init complains with an incomplete .cqfdrc"
+jtest_prepare "cqfd --init complains with an incomplete .cqfdrc"
 echo '[project]' >"$TDIR/.cqfdrc"
-if ! "$cqfd" init; then
+if ! "$cqfd" --init; then
 	jtest_result pass
 else
 	jtest_result fail
diff --git a/tests/01-cqfd_init b/tests/01-cqfd_init
--- a/tests/01-cqfd_init
+++ b/tests/01-cqfd_init
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 #
-# validate the behavior of init command
+# validate the behavior of --init option
 
 set -o pipefail
 
@@ -10,33 +10,33 @@ cqfd="$TDIR/.cqfd/cqfd"
 cd "$TDIR/" || exit 1
 
 ################################################################################
-# 'cqfd init' with a proper .cqfdrc should pass
+# 'cqfd --init' with a proper .cqfdrc should pass
 ################################################################################
-jtest_prepare "run cqfd init"
-if "$cqfd" init; then
+jtest_prepare "cqfd --init"
+if "$cqfd" --init; then
 	jtest_result pass
 else
 	jtest_result fail
 fi
 
 ################################################################################
-# 'cqfd init' with a nonexistent Dockerfile should fail
+# 'cqfd --init' with a nonexistent Dockerfile should fail
 ################################################################################
-jtest_prepare "init with a nonexisting dockerfile shall fail"
+jtest_prepare "cqfd --init with a nonexisting dockerfile shall fail"
 cp -f .cqfdrc .cqfdrc.orig
 sed -i -e "s/\[build\]/[build]\ndistro='thisshouldfail'/" .cqfdrc
-if ! "$cqfd" init; then
+if ! "$cqfd" --init; then
 	jtest_result pass
 else
 	jtest_result fail
 fi
 
 ################################################################################
-# 'cqfd init' with a proper Dockerfile should pass
+# 'cqfd --init' with a proper Dockerfile should pass
 ################################################################################
-jtest_prepare "run cqfd init with an other Dockerfile"
+jtest_prepare "cqfd --init with an other Dockerfile"
 sed -i -e "s/thisshouldfail/centos/" .cqfdrc
-if "$cqfd" init; then
+if "$cqfd" --init true; then
 	jtest_result pass
 else
 	jtest_result fail
@@ -45,24 +45,24 @@ fi
 mv -f .cqfdrc.orig .cqfdrc
 
 ################################################################################
-# 'cqfd init' with same uid/gid dummy user should pass
+# 'cqfd --init' with same uid/gid dummy user/group should pass
 ################################################################################
-jtest_prepare "add dummy user and dummy group with same uid/gid"
+jtest_prepare "cqfd --init with same uid/gid dummy user/group"
 cat <<EOF >>.cqfd/docker/Dockerfile
 RUN groupadd -og "${GROUPS[0]}" -f dummy && \
     useradd -s /bin/bash -ou "$UID" -g "${GROUPS[0]}" dummy
 EOF
-if "$cqfd" init; then
+if "$cqfd" --init; then
 	jtest_result pass
 else
 	jtest_result fail
 fi
 
 ################################################################################
-# 'cqfd init' in quiet mode should be quiet
+# 'cqfd --init' in quiet mode should be quiet
 ################################################################################
-jtest_prepare "cqfd -q init should remain quiet"
-if ! "$cqfd" -q init | grep -E "^(sha256:)?[a-f0-9]{64}$"; then
+jtest_prepare "cqfd -q --init should remain quiet"
+if ! "$cqfd" -q --init | grep -E "^(sha256:)?[a-f0-9]{64}$"; then
 	jtest_result fail
 else
 	jtest_result pass
diff --git a/tests/05-cqfd_init_alt_ext b/tests/05-cqfd_init_alt_ext
--- a/tests/05-cqfd_init_alt_ext
+++ b/tests/05-cqfd_init_alt_ext
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 #
-# validate the behavior of init with alternate file and external directory
+# validate the behavior of --init option with alternate file and external directory
 
 . "$(dirname "$0")/jtest.inc" "$1"
 
@@ -17,76 +17,76 @@ mv .cqfdrc "$extdir/cqfdrc"
 cqfd="$TDIR/$extdir/cqfd/cqfd"
 
 ################################################################################
-# 'cqfd init' without local files should fail
+# 'cqfd --init' without local files should fail
 ################################################################################
-jtest_prepare "cqfd init without local files should fail"
-if ! "$cqfd" init; then
+jtest_prepare "cqfd --init without local files should fail"
+if ! "$cqfd" --init; then
 	jtest_result pass
 else
 	jtest_result fail
 fi
 
 ################################################################################
-# 'cqfd init' using alternate filenames in an external directory using filenames
-# should work
-################################################################################
-jtest_prepare "cqfd init using alternate filenames in an external directory using filenames using options should work"
-if "$cqfd" -C "$extdir" -d cqfd -f cqfdrc init; then
-	jtest_result pass
-else
-	jtest_result fail
-fi
-
-################################################################################
-# 'cqfd init' using alternate filenames in an external directory using absolute
+# 'cqfd --init' using alternate filenames in an external directory using
 # filenames should work
 ################################################################################
-jtest_prepare "cqfd init using alternate filenames in an external directory using relative filenames using options should work"
-if "$cqfd" -d "$extdir/cqfd" -f "$extdir/cqfdrc" init; then
+jtest_prepare "cqfd --init using alternate filenames in an external directory using filenames using options should work"
+if "$cqfd" -C "$extdir" -d cqfd -f cqfdrc --init; then
 	jtest_result pass
 else
 	jtest_result fail
 fi
 
 ################################################################################
-# 'cqfd init' using alternate filenames in an external directory using absolute
+# 'cqfd --init' using alternate filenames in an external directory using
+# absolute filenames should work
+################################################################################
+jtest_prepare "cqfd --init using alternate filenames in an external directory using relative filenames using options should work"
+if "$cqfd" -d "$extdir/cqfd" -f "$extdir/cqfdrc" --init; then
+	jtest_result pass
+else
+	jtest_result fail
+fi
+
+################################################################################
+# 'cqfd --init' using alternate filenames in an external directory using
+# absolute filenames should work
+################################################################################
+jtest_prepare "cqfd --init using alternate filenames in an external directory using absolute using options filenames should work"
+if "$cqfd" -d "$PWD/$extdir/cqfd" -f "$PWD/$extdir/cqfdrc" --init; then
+	jtest_result pass
+else
+	jtest_result fail
+fi
+
+################################################################################
+# 'cqfd --init' using alternate filenames in an external directory using
 # filenames should work
 ################################################################################
-jtest_prepare "cqfd init using alternate filenames in an external directory using absolute using options filenames should work"
-if "$cqfd" -d "$PWD/$extdir/cqfd" -f "$PWD/$extdir/cqfdrc" init; then
+jtest_prepare "cqfd --init using alternate filenames in an external directory using filenames using environment variables should work"
+if CQFD_DIR=cqfd CQFDRC_FILE=cqfdrc "$cqfd" -C "$extdir" --init; then
 	jtest_result pass
 else
 	jtest_result fail
 fi
 
 ################################################################################
-# 'cqfd init' using alternate filenames in an external directory using filenames
-# should work
+# 'cqfd --init' using alternate filenames in an external directory using
+# absolute filenames should work
 ################################################################################
-jtest_prepare "cqfd init using alternate filenames in an external directory using filenames using environment variables should work"
-if CQFD_DIR=cqfd CQFDRC_FILE=cqfdrc "$cqfd" -C "$extdir" init; then
+jtest_prepare "cqfd --init using alternate filenames in an external directory using relative filenames using environment variables should work"
+if CQFD_DIR="$extdir/cqfd" CQFDRC_FILE="$extdir/cqfdrc" "$cqfd" --init; then
 	jtest_result pass
 else
 	jtest_result fail
 fi
 
 ################################################################################
-# 'cqfd init' using alternate filenames in an external directory using absolute
-# filenames should work
+# 'cqfd --init' using alternate filenames in an external directory using
+# absolute filenames should work
 ################################################################################
-jtest_prepare "cqfd init using alternate filenames in an external directory using relative filenames using environment variables should work"
-if CQFD_DIR="$extdir/cqfd" CQFDRC_FILE="$extdir/cqfdrc" "$cqfd" init; then
-	jtest_result pass
-else
-	jtest_result fail
-fi
-
-################################################################################
-# 'cqfd init' using alternate filenames in an external directory using absolute
-# filenames should work
-################################################################################
-jtest_prepare "cqfd init using alternate filenames in an external directory using absolute filenames using environment variables should work"
-if CQFD_DIR="$PWD/$extdir/cqfd" CQFDRC_FILE="$PWD/$extdir/cqfdrc" "$cqfd" init; then
+jtest_prepare "cqfd --init using alternate filenames in an external directory using absolute filenames using environment variables should work"
+if CQFD_DIR="$PWD/$extdir/cqfd" CQFDRC_FILE="$PWD/$extdir/cqfdrc" "$cqfd" --init; then
 	jtest_result pass
 else
 	jtest_result fail
diff --git a/tests/05-cqfd_init_extra_env b/tests/05-cqfd_init_extra_env
--- a/tests/05-cqfd_init_extra_env
+++ b/tests/05-cqfd_init_extra_env
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 #
-# validate the behavior of init with extra build environment variable
+# validate the behavior of --init option with extra build environment variable
 
 . "$(dirname "$0")/jtest.inc" "$1"
 cqfd="$TDIR/.cqfd/cqfd"
@@ -14,21 +14,21 @@ cp -f .cqfd/docker/Dockerfile .cqfd/docker/Dockerfile.orig
 cp -f .cqfd/docker/Dockerfile.init_extra_env .cqfd/docker/Dockerfile
 
 ################################################################################
-# 'cqfd init' without CQFD_EXTRA_BUILD_ARGS should fail
+# 'cqfd --init' without CQFD_EXTRA_BUILD_ARGS should fail
 ################################################################################
-jtest_prepare "cqfd init without using CQFD_EXTRA_BUILD_ARGS"
-if ! "$cqfd" init; then
+jtest_prepare "cqfd --init without using CQFD_EXTRA_BUILD_ARGS"
+if ! "$cqfd" --init; then
 	jtest_result pass
 else
 	jtest_result fail
 fi
 
 ################################################################################
-# 'cqfd init' with CQFD_EXTRA_BUILD_ARGS should succeed
+# 'cqfd --init' with CQFD_EXTRA_BUILD_ARGS should succeed
 ################################################################################
-jtest_prepare "cqfd init using CQFD_EXTRA_BUILD_ARGS"
+jtest_prepare "cqfd --init using CQFD_EXTRA_BUILD_ARGS"
 export CQFD_EXTRA_BUILD_ARGS="--build-arg FOO=foo --no-cache"
-if "$cqfd" init; then
+if "$cqfd" --init true; then
 	jtest_result pass
 else
 	jtest_result fail
diff --git a/tests/05-cqfd_init_flavor b/tests/05-cqfd_init_flavor
--- a/tests/05-cqfd_init_flavor
+++ b/tests/05-cqfd_init_flavor
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 #
-# validate the behavior of init command with flavors
+# validate the behavior of --init option with flavors
 
 set -o pipefail
 
@@ -11,13 +11,13 @@ flavor="foo"
 cd "$TDIR/" || exit 1
 
 ################################################################################
-# 'cqfd init' with different flavor makes a different container
+# 'cqfd --reinit' with different flavor makes a different container
 ################################################################################
 cp -f .cqfdrc .cqfdrc.orig
 sed -i -e "s/\[foo\]/[foo]\ndistro='centos'/" .cqfdrc
 
-jtest_prepare "cqfd init using '$flavor' flavor"
-if "$cqfd" -b "$flavor" --reinit run "grep '^NAME=' /etc/*release" | grep -q 'NAME="CentOS Linux"'; then
+jtest_prepare "cqfd --reinit using '$flavor' flavor"
+if "$cqfd" -b "$flavor" --reinit grep '^NAME=' /etc/os-release | grep -q 'NAME="CentOS Linux"'; then
 	jtest_result pass
 else
 	jtest_result fail
@@ -26,21 +26,21 @@ fi
 mv -f .cqfdrc.orig .cqfdrc
 
 ################################################################################
-# 'cqfd init' with invalid flavor should fail
+# 'cqfd --reinit' with invalid flavor should fail
 ################################################################################
 flavorPart="${flavor:0:2}"
-jtest_prepare "cqfd init using part of '$flavor' flavor should fail"
-if ! "$cqfd" -b "$flavorPart" init; then
+jtest_prepare "cqfd --reinit using part of '$flavor' flavor should fail"
+if ! "$cqfd" -b "$flavorPart" --reinit; then
 	jtest_result pass
 else
 	jtest_result fail
 fi
 
 ################################################################################
-# 'cqfd init' without flavor generates our regular container
+# 'cqfd --reinit' without flavor generates our regular container
 ################################################################################
-jtest_prepare "cqfd init without flavor"
-if "$cqfd" --reinit run "grep '^NAME=' /etc/*release" | grep -q 'NAME="Ubuntu"'; then
+jtest_prepare "cqfd --reinit without flavor"
+if "$cqfd" --reinit grep '^NAME=' /etc/os-release | grep -q 'NAME="Ubuntu"'; then
 	jtest_result pass
 else
 	jtest_result fail
diff --git a/tests/05-cqfd_run b/tests/05-cqfd_run
--- a/tests/05-cqfd_run
+++ b/tests/05-cqfd_run
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 #
-# validate the behavior of run command
+# validate the behavior of CLI
 
 . "$(dirname "$0")/jtest.inc" "$1"
 cqfd="$TDIR/.cqfd/cqfd"
@@ -8,44 +8,35 @@ test_file="a/cqfd_a.txt"
 
 cd "$TDIR/" || exit 1
 
-# Here we test cqfd run, which is also invoked without any argument
-for i in 0 1; do
-	# Data set shall produce a/cqfd_a.txt:
-
-	if [ -f "$test_file" ]; then
-		jtest_log fatal "$test_file already present before test"
-		rm -f "$test_file"
-		continue
-	fi
-
-	if [ "$i" = "1" ]; then
-		jtest_prepare "running \"cqfd run\" makes it run"
-		"$cqfd" run
-	else
-		jtest_prepare "running \"cqfd\" with no argument makes it run"
-		"$cqfd"
-	fi
-
-	# at the end of either test, $test_file is populated
-	if grep -qw "cqfd" "$test_file"; then
-		jtest_result pass
-	else
-		jtest_log fatal "$test_file not present after test"
-		jtest_result fail
-		rm -f "$test_file"
-		continue
-	fi
-
-	rm -f "$test_file"
-done
+################################################################################
+# 'cqfd' runs command set in .cqfdrc
+################################################################################
+jtest_prepare "cqfd run command set in .cqfdrc"
+if "$cqfd" && grep -qw "cqfd" "$test_file"; then
+	jtest_result pass
+else
+	jtest_result fail
+fi
+rm -f "$test_file"
 
 ################################################################################
-# If the Dockerfile changed and no init is done again, 'cqfd run' should fail
+# 'cqfd' runs command overriden by the command line
+################################################################################
+jtest_prepare "cqfd run command overriden by the command-line"
+if "$cqfd" touch "$test_file" && test -e "$test_file" && ! test -s "$test_file"; then
+	jtest_result pass
+else
+	jtest_result fail
+fi
+rm -f "$test_file"
+
+################################################################################
+# If the Dockerfile changed and no init is done again, 'cqfd' should fail
 ################################################################################
 jtest_prepare "Modifying the Dockerfile should require running 'cqfd init' again"
 dockerfile=.cqfd/docker/Dockerfile
 echo "RUN echo $RANDOM" >>"$dockerfile"
-if ! "$cqfd" run; then
+if ! "$cqfd"; then
 	jtest_result pass
 else
 	jtest_result fail
diff --git a/tests/05-cqfd_run_c_flavor b/tests/05-cqfd_run_c_flavor
--- a/tests/05-cqfd_run_c_flavor
+++ b/tests/05-cqfd_run_c_flavor
@@ -1,33 +1,34 @@
 #!/usr/bin/env bash
 #
-# validate the behavior of run -c command
+# validate the behavior -c option
 
 . "$(dirname "$0")/jtest.inc" "$1"
 cqfd="$TDIR/.cqfd/cqfd"
 flavor="foo"
 test_file="$flavor"
-test_run_c_file="test_run_c.txt"
+test_c_file="test_c.txt"
 fail=0
 
 cd "$TDIR/" || exit 1
 
-if [ -f "$test_file" ] || [ -f "$test_run_c_file" ]; then
-	jtest_log info "$test_file or $test_run_c_file already present before test, removing..."
+if [ -f "$test_file" ] || [ -f "$test_c_file" ]; then
+	jtest_log info "$test_file or $test_c_file already present before test, removing..."
 	rm -f "$test_file"
-	rm -f "$test_run_c_file"
+	rm -f "$test_c_file"
 fi
 
-jtest_prepare "build cmd for '$flavor' flavor and concatenate with an additional option"
-if ! "$cqfd" -b "$flavor" run -c --debug >"$test_run_c_file"; then
-	jtest_log fatal "cqfd run -c --debug failed"
+jtest_prepare "cqfd -c with a given '$flavor' flavor concatenate additional option"
+if ! "$cqfd" -b "$flavor" -c --debug >"$test_c_file"; then
+	jtest_log fatal "cqfd -c --debug failed"
 	fail=1
+	rm -f "$test_c_file"
 fi
 
-# at the end of this test, $test_run_c_file is populated
-if ! grep -qw "target 'foo'" "$test_run_c_file"; then
-	jtest_log fatal "$test_run_c_file not present after test"
+# at the end of this test, $test_c_file is populated
+if ! grep -qw "target 'foo'" "$test_c_file"; then
+	jtest_log fatal "$test_c_file not present after test"
 	fail=1
-	rm -f "$test_run_c_file"
+	rm -f "$test_c_file"
 fi
 
 # at the end of either test, $test_file is populated
@@ -44,4 +45,4 @@ else
 fi
 
 rm -f "$test_file"
-rm -f "$test_run_c_file"
+rm -f "$test_c_file"
diff --git a/tests/05-cqfd_run_check_dependencies b/tests/05-cqfd_run_check_dependencies
--- a/tests/05-cqfd_run_check_dependencies
+++ b/tests/05-cqfd_run_check_dependencies
@@ -23,7 +23,7 @@ cp -f .cqfd/docker/Dockerfile.missing_dependencies .cqfd/docker/Dockerfile
 # Missing all core dependencies for the launch script
 ################################################################################
 jtest_prepare "cqfd run fails when the Docker image lacks required commands"
-if "$cqfd" --reinit run; then
+if "$cqfd" --init run; then
 	jtest_result pass
 else
 	jtest_result fail
@@ -35,13 +35,13 @@ fi
 echo 'RUN apk add bash shadow' >>.cqfd/docker/Dockerfile
 
 ################################################################################
-# cqfd run should now be happy with the required commands, using su.
+# cqfd should now be happy with the required commands, using su.
 ################################################################################
-jtest_prepare "cqfd run with satisfied command requirements, using su"
+jtest_prepare "cqfd with satisfied command requirements, using su"
 if [ "${cqfd_docker[-1]}" = "podman" ]; then
 	jtest_result skip
 else
-	if "$cqfd" --reinit --verbose run true \
+	if "$cqfd" --reinit --verbose true \
 		| awk -v rc=1 '/Using "su"/ { rc=0 } 1; END {exit rc}'; then
 		jtest_result pass
 	else
@@ -55,13 +55,13 @@ fi
 echo 'RUN apk add sudo' >>.cqfd/docker/Dockerfile
 
 ################################################################################
-# cqfd run should now be happy with the required commands, using sudo
+# cqfd should now be happy with the required commands, using sudo
 ################################################################################
-jtest_prepare "cqfd run with satisfied command requirements, using sudo"
+jtest_prepare "cqfd with satisfied command requirements, using sudo"
 if [ "${cqfd_docker[-1]}" = "podman" ]; then
 	jtest_result skip
 else
-	if "$cqfd" --reinit --verbose run true \
+	if "$cqfd" --reinit --verbose true \
 		| awk -v rc=1 '/Using "sudo"/ { rc=0 } 1; END {exit rc}'; then
 		jtest_result pass
 	else
@@ -74,6 +74,6 @@ fi
 ################################################################################
 mv -f .cqfd/docker/Dockerfile.orig .cqfd/docker/Dockerfile
 jtest_log info "restore container"
-if ! "$cqfd" init; then
-	jtest_log error "cqfd init failed"
+if ! "$cqfd" --init; then
+	jtest_log error "cqfd --init failed"
 fi
diff --git a/tests/05-cqfd_run_su_or_sudo_backend b/tests/05-cqfd_run_su_or_sudo_backend
--- a/tests/05-cqfd_run_su_or_sudo_backend
+++ b/tests/05-cqfd_run_su_or_sudo_backend
@@ -26,7 +26,7 @@ jtest_prepare "cqfd run with su -c"
 if [ "${cqfd_docker[-1]}" = "podman" ]; then
 	jtest_result skip
 else
-	if "$cqfd" --reinit --verbose run true \
+	if "$cqfd" --reinit --verbose true \
 		| awk -v rc=1 '/Using "su" to execute command/ { rc=0 } 1; END {exit rc}'; then
 		jtest_result pass
 	else
@@ -46,7 +46,7 @@ jtest_prepare "cqfd run with su --session-command"
 if [ "${cqfd_docker[-1]}" = "podman" ]; then
 	jtest_result skip
 else
-	if "$cqfd" --reinit --verbose run true \
+	if "$cqfd" --reinit --verbose true \
 		| awk -v rc=1 '/Using "su" to execute session command/ { rc=0 } 1; END {exit rc}'; then
 		jtest_result pass
 	else
@@ -67,7 +67,7 @@ jtest_prepare "cqfd run with sudo"
 if [ "${cqfd_docker[-1]}" = "podman" ]; then
 	jtest_result skip
 else
-	if "$cqfd" --reinit --verbose run true \
+	if "$cqfd" --reinit --verbose true \
 		| awk -v rc=1 '/Using "sudo" to execute command/ { rc=0 } 1; END {exit rc}'; then
 		jtest_result pass
 	else
@@ -80,6 +80,6 @@ fi
 ################################################################################
 mv -f .cqfd/docker/Dockerfile.orig .cqfd/docker/Dockerfile
 jtest_log info "restore container"
-if ! "$cqfd" init; then
-	jtest_log fatal "cqfd init failed"
+if ! "$cqfd" --init; then
+	jtest_log fatal "cqfd --init failed"
 fi
diff --git a/tests/06-cqfd_release b/tests/06-cqfd_release
--- a/tests/06-cqfd_release
+++ b/tests/06-cqfd_release
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 #
-# validate the behavior of release command
+# validate the behavior of option --release
 
 set -o pipefail
 
@@ -13,8 +13,8 @@ cd "$TDIR/" || exit 1
 # The first invocation has no 'files' parameter defined,
 # hence it should fail
 ################################################################################
-jtest_prepare "cqfd release fails without files parameter"
-if ! "$cqfd" release; then
+jtest_prepare "cqfd --release fails without files parameter"
+if ! "$cqfd" --release; then
 	jtest_result pass
 else
 	jtest_result fail
@@ -26,8 +26,8 @@ fi
 rel_files="a/cqfd_a.txt a/b/c/cqfd_c.txt a/b/cqfd_b.txt"
 cp -f .cqfdrc .cqfdrc.orig
 echo "files=\"$rel_files\"" >>.cqfdrc
-jtest_prepare "cqfd release now with a files parameter"
-if "$cqfd" release; then
+jtest_prepare "cqfd --release now with a files parameter"
+if "$cqfd" --release; then
 	jtest_result pass
 else
 	jtest_result fail
@@ -57,7 +57,7 @@ rm -f cqfd-test.tar.xz
 # now use tar_transform=no
 jtest_prepare "archived files NOT at root of tar archive if tar_transform=no"
 echo "tar_transform=no" >>.cqfdrc
-if "$cqfd" release; then
+if "$cqfd" --release; then
 	result="pass"
 else
 	result="fail"
@@ -74,7 +74,7 @@ rm -f cqfd-test.tar.xz
 # now use tar_transform=yes
 jtest_prepare "archived files at root of tar archive if tar_transform=yes"
 echo "tar_transform=yes" >>.cqfdrc
-if "$cqfd" release; then
+if "$cqfd" --release; then
 	result="pass"
 else
 	result="fail"
@@ -94,7 +94,7 @@ rm -f cqfd-test.tar.xz
 ################################################################################
 jtest_prepare "symlink files are copied in the tar archive"
 result="pass"
-if ! "$cqfd" run ln -s a/cqfd_a.txt link.txt; then
+if ! "$cqfd" ln -s a/cqfd_a.txt link.txt; then
 	jtest_log fatal "cqfd run failed"
 	result="fail"
 fi
@@ -103,8 +103,8 @@ sed -i '/files=/d' .cqfdrc
 echo "files=\"$rel_files_link\"" >>.cqfdrc
 echo "tar_options=-h" >>.cqfdrc
 
-if ! "$cqfd" release; then
-	jtest_log fatal "cqfd release failed"
+if ! "$cqfd" --release; then
+	jtest_log fatal "cqfd --release failed"
 	result="fail"
 fi
 mkdir "$TDIR/output"
@@ -136,7 +136,7 @@ export CTEST=foobar
 d3="$(date --rfc-3339='date')"
 # shellcheck disable=SC2016
 echo 'archive=cqfd-%D3-$CTEST.tar.xz' >>.cqfdrc
-if "$cqfd" release && tar tf "cqfd-$d3-foobar.tar.xz" &>/dev/null; then
+if "$cqfd" --release && tar tf "cqfd-$d3-foobar.tar.xz" &>/dev/null; then
 	jtest_result pass
 else
 	jtest_result fail
@@ -147,7 +147,7 @@ jtest_prepare "build.archive can template filenames (git short hash of last comm
 # shellcheck disable=SC2016
 sed -i -e '$ s!^archive=.*$!archive=cqfd-%Gh-$CTEST.tar.xz!' .cqfdrc
 # shellcheck disable=SC2010
-if "$cqfd" release &&
+if "$cqfd" --release &&
    ls -1 cqfd-*-foobar.tar.xz | grep -qE "^cqfd-([[:xdigit:]]{4,40}|unset)-foobar.tar.xz$" &&
    tar tf cqfd-*-foobar.tar.xz &>/dev/null; then
 	jtest_result pass
@@ -160,7 +160,7 @@ jtest_prepare "build.archive can template filenames (git long hash of last commi
 # shellcheck disable=SC2016
 sed -i -e '$ s!^archive=.*$!archive=cqfd-%GH-$CTEST.tar.xz!' .cqfdrc
 # shellcheck disable=SC2010
-if "$cqfd" release &&
+if "$cqfd" --release &&
    ls -1 cqfd-*-foobar.tar.xz | grep -qE "^cqfd-([[:xdigit:]]{40}|unset)-foobar.tar.xz$" &&
    tar tf cqfd-*-foobar.tar.xz &>/dev/null; then
 	jtest_result pass
@@ -173,7 +173,7 @@ jtest_prepare "build.archive can template filenames (Unix timestamp)"
 # shellcheck disable=SC2016
 sed -i -e '$ s!^archive=.*$!archive=cqfd-%Du-$CTEST.tar.xz!' .cqfdrc
 # shellcheck disable=SC2010
-if "$cqfd" release &&
+if "$cqfd" --release &&
    ls -1 cqfd-*-foobar.tar.xz | grep -q "^cqfd-[[:digit:]]\{1,20\}-foobar.tar.xz$" &&
    tar tf cqfd-*-foobar.tar.xz &>/dev/null; then
 	jtest_result pass
@@ -185,7 +185,7 @@ rm -f cqfd-*-foobar.tar.xz
 jtest_prepare "build.archive can template filenames (current cqfd flavor name unset)"
 # shellcheck disable=SC2016
 sed -i -e '$ s!^archive=.*$!archive=cqfd-%Cf-$CTEST.tar.xz!' .cqfdrc
-if "$cqfd" release && tar tf cqfd--foobar.tar.xz &>/dev/null; then
+if "$cqfd" --release && tar tf cqfd--foobar.tar.xz &>/dev/null; then
 	jtest_result pass
 else
 	jtest_result fail
@@ -193,7 +193,7 @@ fi
 rm -f cqfd--foobar.tar.xz
 
 jtest_prepare "build.archive can template filenames (current cqfd flavor name set)"
-if "$cqfd" -b foo release && tar tf cqfd-foo.tar.xz &>/dev/null; then
+if "$cqfd" -b foo --release && tar tf cqfd-foo.tar.xz &>/dev/null; then
 	jtest_result pass
 else
 	jtest_result fail
@@ -203,7 +203,7 @@ rm -f cqfd-foo.tar.xz
 jtest_prepare "build.archive can template filenames (value of the project.org configuration key)"
 # shellcheck disable=SC2016
 sed -i -e '$ s!^archive=.*$!archive=cqfd-%Po-$CTEST.tar.xz!' .cqfdrc
-if "$cqfd" release && tar tf cqfd-cqfd-foobar.tar.xz &>/dev/null; then
+if "$cqfd" --release && tar tf cqfd-cqfd-foobar.tar.xz &>/dev/null; then
 	jtest_result pass
 else
 	jtest_result fail
@@ -213,7 +213,7 @@ rm -f cqfd-cqfd-foobar.tar.xz
 jtest_prepare "build.archive can template filenames (value of the project.name configuration key)"
 # shellcheck disable=SC2016
 sed -i -e '$ s!^archive=.*$!archive=cqfd-%Pn-$CTEST.tar.xz!' .cqfdrc
-if "$cqfd" release && tar tf cqfd-test-foobar.tar.xz &>/dev/null; then
+if "$cqfd" --release && tar tf cqfd-test-foobar.tar.xz &>/dev/null; then
 	jtest_result pass
 else
 	jtest_result fail
@@ -223,7 +223,7 @@ rm -f cqfd-test-foobar.tar.xz
 jtest_prepare "build.archive can template filenames (litteral '%' sign)"
 # shellcheck disable=SC2016
 sed -i -e '$ s!^archive=.*!archive=cqfd-%%-$CTEST.tar.xz!' .cqfdrc
-if "$cqfd" release && tar tf cqfd-%-foobar.tar.xz &>/dev/null; then
+if "$cqfd" --release && tar tf cqfd-%-foobar.tar.xz &>/dev/null; then
 	jtest_result pass
 else
 	jtest_result fail
@@ -236,7 +236,7 @@ rm -f cqfd-%-foobar.tar.xz
 jtest_prepare "build.archive can make a .tar.gz archive"
 # shellcheck disable=SC2016
 sed -i -e '$ s!^archive=.*xz$!archive=cqfd-$CTEST.tar.gz!' .cqfdrc
-if "$cqfd" release && tar ztf "cqfd-$CTEST.tar.gz" &>/dev/null; then
+if "$cqfd" --release && tar ztf "cqfd-$CTEST.tar.gz" &>/dev/null; then
 	jtest_result pass
 else
 	jtest_result fail
@@ -249,7 +249,7 @@ rm -f "cqfd-$CTEST.tar.gz"
 jtest_prepare "build.archive can make a .zip archive"
 # shellcheck disable=SC2016
 sed -i -e '$ s!^archive=.*gz$!archive=cqfd-$CTEST.zip!' .cqfdrc
-if "$cqfd" release && unzip -l "cqfd-$CTEST.zip" &>/dev/null; then
+if "$cqfd" --release && unzip -l "cqfd-$CTEST.zip" &>/dev/null; then
 	jtest_result pass
 else
 	jtest_result fail
@@ -263,7 +263,7 @@ for flav in foo bar; do
 	filename="cqfd-$flav.tar.xz"
 	jtest_prepare "release for flavor $flav creates $filename"
 
-	"$cqfd" -b "$flav" release
+	"$cqfd" -b "$flav" --release
 	if tar tf "$filename" &>/dev/null; then
 		jtest_result pass
 	else
@@ -277,7 +277,7 @@ done
 ################################################################################
 jtest_prepare "cqfd fails on missing file in build.files"
 sed -i -e 's!^files=.*$!files="ThisFileDoesNotExist.txt"!' .cqfdrc
-if ! "$cqfd" release; then
+if ! "$cqfd" --release; then
 	jtest_result pass
 else
 	jtest_result fail
@@ -291,7 +291,7 @@ jtest_prepare "cqfd resolves globs in build.files"
 sed -i -e 's!^archive=.*$!archive=cqfd-$CTEST.tar.xz!' .cqfdrc
 sed -i -e 's!^files=.*$!files=".cq*rc Ma*"!' .cqfdrc
 # cqfd release must work without error
-if "$cqfd" release; then
+if "$cqfd" --release; then
 	jtest_result pass
 else
 	jtest_result fail
