cqfd: run sudo if not in docker group
The docker client requires to run as root in rootfull mode. The docker
group allows a user to access to the Unix socket created by the docker
daemon.

The user needs to run docker client with more privileges (i.e. sudo) if
it is not part of that group[1].

This prepends sudo to CQFD_DOCKER automatically if CQFD_RUN_WITH_SUDO is
set to true. It turns the internal variable cqfd_docket into an array to
split the command into pieces ("sudo docker" -> "sudo" and "docker").

Note: ls and gc commands run docker, thus, both commands require to call
load_config() that sets the cqfd_docker "binary" to exec if user is not
in the docker group and if CQFD_RUN_WITH_SUDO is set.

[1]: https://docs.docker.com/install/linux/linux-postinstall/#manage-docker-as-a-non-root-user

diff --git a/tests/00-setup b/tests/00-setup
--- a/tests/00-setup
+++ b/tests/00-setup
@@ -11,20 +11,20 @@ cqfd="$TDIR/.cqfd/cqfd"
 cd "$TDIR/" || exit 1
 
 ################################################################################
-# running 'cqfd ls' without a proper config and empty cache should pass
+# running 'cqfd ls' without a proper config should fail
 ################################################################################
-jtest_prepare "cqfd ls runs without an .cqfdrc and with an empty cache"
-if "$cqfd" ls; then
+jtest_prepare "cqfd ls complains without an .cqfdrc"
+if ! "$cqfd" ls; then
 	jtest_result pass
 else
 	jtest_result fail
 fi
 
 ################################################################################
-# running 'cqfd gc' without a proper config and empty cache should pass
+# running 'cqfd gc' without a proper config should fail
 ################################################################################
-jtest_prepare "cqfd gc runs without an .cqfdrc and with an empty cache"
-if "$cqfd" gc; then
+jtest_prepare "cqfd gc complains without an .cqfdrc"
+if ! "$cqfd" gc; then
 	jtest_result pass
 else
 	jtest_result fail
