tests: 00-setup: add testing for missing .cqfd directory
This adds testing for missing .cqfd directory.

diff --git a/tests/00-setup b/tests/00-setup
--- a/tests/00-setup
+++ b/tests/00-setup
@@ -3,7 +3,6 @@
 # validate the behavior with skelton bring up
 
 . "$(dirname "$0")/jtest.inc" "$1"
-mkdir -p "$TDIR/.cqfd/docker"
 mkdir -p "$TDIR/.local/bin"
 cp -a ../cqfd "$TDIR/.local/bin/cqfd$CQFD_COMPAT"
 ln -sf "cqfd$CQFD_COMPAT" "$TDIR/.local/bin/cqfd"
@@ -11,6 +10,21 @@ cp -a test_data/. "$TDIR/."
 cqfd="$TDIR/.local/bin/cqfd"
 
 cd "$TDIR/" || exit 1
+
+################################################################################
+# running 'cqfd init' without a proper config directory should fail
+################################################################################
+jtest_prepare "cqfd init complains without an .cqfd directory"
+if ! "$cqfd" init; then
+	jtest_result pass
+else
+	jtest_result fail
+fi
+
+################################################################################
+# initially, for setup, insert a proper testing .cqfd directory
+################################################################################
+mv cqfd .cqfd
 
 ################################################################################
 # running 'cqfd ls' without a proper config file should fail
