tests: 01-cqfd_init: restore Dockerfile and container at teardown
This restores the Dockerfile and the container after the end of tests.

See commit 26a4a37cffafa34e5532dc1c5667376c7d7bf193.

diff --git a/tests/01-cqfd_init b/tests/01-cqfd_init
--- a/tests/01-cqfd_init
+++ b/tests/01-cqfd_init
@@ -9,6 +9,11 @@ set -o pipefail
 cd "$TDIR/" || exit 1
 
 ################################################################################
+# Create a special test context
+################################################################################
+cp -f .cqfd/docker/Dockerfile .cqfd/docker/Dockerfile.orig
+
+################################################################################
 # 'cqfd init' with a proper .cqfdrc file should pass
 ################################################################################
 jtest_prepare "run cqfd init"
@@ -65,4 +70,16 @@ if ! cqfd -q init | grep -E "^(sha256:)?[a-f0-9]{64}$"; then
 	jtest_result fail
 else
 	jtest_result pass
+fi
+
+################################################################################
+# restore initial Dockerfile
+################################################################################
+mv -f .cqfd/docker/Dockerfile.orig .cqfd/docker/Dockerfile
+
+################################################################################
+# restore container
+################################################################################
+if ! cqfd init; then
+	jtest_log error "restore container failed"
 fi
