cqfd: default to cqfd run
In order to have cqfd to run similarly to known tools, such as sudo,
the cqfd run command has been removed as the default command is now
"run".

Tests have been updated automatically using the following commands:

 $ sed -i 's/cqfd run/cqfd/g' tests/0*
 $ sed -i -s 's/cqfd(.*) init/cqfd\1 --init/g' tests/0*
 $ sed -i -s 's/cqfd(.*) release/cqfd\1 --release/g' tests/0*
 $ sed -i -s 's/cqfd(.*) flavors/cqfd\1 --flavors/g' tests/0*
 $ sed -i -s 's/cqfd(.*) version/cqfd\1 --version/g' tests/0*

and by manually running the test suite for missing $ cqfd.+ run
commands.

diff --git a/tests/01-cqfd_init b/tests/01-cqfd_init
--- a/tests/01-cqfd_init
+++ b/tests/01-cqfd_init
@@ -10,34 +10,34 @@ cqfd="$TDIR"/.cqfd/cqfd
 cd "$TDIR/" || exit 1
 
 ################################################################################
-# 'cqfd init' with a proper .cqfdrc should pass
+# 'cqfd --init' with a proper .cqfdrc should pass
 ################################################################################
-jtest_prepare "run cqfd init"
-if "$cqfd" init; then
+jtest_prepare "run cqfd --init"
+if "$cqfd" --init; then
 	jtest_result pass
 else
 	jtest_result fail
 fi
 
 ################################################################################
-# 'cqfd init' with a nonexistent Dockerfile should fail
+# 'cqfd --init' with a nonexistent Dockerfile should fail
 ################################################################################
 cqfdrc_old=$(mktemp)
 jtest_prepare "init with a nonexisting dockerfile shall fail"
 cp -f .cqfdrc "$cqfdrc_old"
 sed -i -e "s/\[build\]/[build]\ndistro='thisshouldfail'/" .cqfdrc
-if "$cqfd" init; then
+if "$cqfd" --init; then
 	jtest_result fail
 else
 	jtest_result pass
 fi
 
 ################################################################################
-# 'cqfd init' with a proper Dockerfile should pass
+# 'cqfd --init' with a proper Dockerfile should pass
 ################################################################################
-jtest_prepare "run cqfd init with an other Dockerfile"
+jtest_prepare "run cqfd --init with an other Dockerfile"
 sed -i -e "s/thisshouldfail/centos/" .cqfdrc
-if "$cqfd" init; then
+if "$cqfd" --init; then
 	jtest_result pass
 else
 	jtest_result fail
@@ -46,24 +46,24 @@ fi
 mv -f "$cqfdrc_old" .cqfdrc
 
 ################################################################################
-# 'cqfd init' with same uid/gid dummy user should pass
+# 'cqfd --init' with same uid/gid dummy user should pass
 ################################################################################
 jtest_prepare "add dummy user and dummy group with same uid/gid"
 cat <<EOF >>.cqfd/docker/Dockerfile
 RUN groupadd -og "${GROUPS[0]}" -f dummy && \
     useradd -s /bin/bash -ou "$UID" -g "${GROUPS[0]}" dummy
 EOF
-if "$cqfd" init; then
+if "$cqfd" --init; then
 	jtest_result pass
 else
 	jtest_result fail
 fi
 
 ################################################################################
-# 'cqfd init' in quiet mode should be quiet
+# 'cqfd --init' in quiet mode should be quiet
 ################################################################################
-jtest_prepare "cqfd -q init should remain quiet"
-if ! "$cqfd" -q init | grep -E "^(sha256:)?[a-f0-9]{64}$"; then
+jtest_prepare "cqfd -q --init should remain quiet"
+if ! "$cqfd" -q --init | grep -E "^(sha256:)?[a-f0-9]{64}$"; then
 	jtest_result fail
 else
 	jtest_result pass
