tests: 03-cqfd_{help,version}: create tmp files in TDIR
mktemp creates a files to /tmp/tmp.XXXXXX if TEMPLATE is not given and
if TMPDIR is unset.

The tests are run in a mktemp directory already[1][2], and that
directory is removed at the end of tests[3] (if the tests are not
interrupted[3]). The directory is pointed by "$TDIR".

Thus, additionnal temporary files and directories can be created in that
directory to avoid having multiple places to clean up during a test or
after the tests. It polutes even more the temporary directory of the
system if files and directories are left uncleaned.

This removes the use of mktemp to create files directly in the existing
temporary directory "$TDIR" to avoid poluting the temporary directory of
the system if the tests are interrupted.

[1]: https://github.com/savoirfairelinux/cqfd/blob/v5.7.0/tests/Makefile#L14
[2]: https://github.com/savoirfairelinux/cqfd/blob/v5.7.0/tests/Makefile#L17
[3]: https://github.com/savoirfairelinux/cqfd/blob/v5.7.0/tests/Makefile#L29-L31

diff --git a/tests/03-cqfd_help b/tests/03-cqfd_help
--- a/tests/03-cqfd_help
+++ b/tests/03-cqfd_help
@@ -9,12 +9,11 @@ cqfd="$TDIR/.cqfd/cqfd"
 # 'cqfd help' shall be an accepted command
 ################################################################################
 jtest_prepare "cqfd help shall exit normally"
-TEST=$(mktemp)
-if "$cqfd" help >"$TEST"; then
+if "$cqfd" help >"$TDIR/usage"; then
 	jtest_result pass
 else
 	jtest_result fail
-	rm -f "$TEST"
+	rm -f "$TDIR/usage"
 fi
 
 ################################################################################
@@ -23,9 +22,9 @@ fi
 jtest_prepare "cqfd help shall produce an help message"
 # Those words shall be present in the output
 for word in Usage Options Commands; do
-	if ! grep -q "^$word:" "$TEST"; then
+	if ! grep -q "^$word:" "$TDIR/usage"; then
 		jtest_log error "cannot find $word in help message"
-		rm -f "$TEST"
+		rm -f "$TDIR/usage"
 		missing=1
 		break
 	fi
@@ -36,4 +35,5 @@ else
 	jtest_result fail
 fi
 
-rm -f "$TEST"
+# cleanup
+rm -f "$TDIR/usage"
