tests: restore containers at teardown
This restores the containers after the end of tests if the Dockerfile
was changed and restored.

diff --git a/tests/04-cqfd_init_context b/tests/04-cqfd_init_context
--- a/tests/04-cqfd_init_context
+++ b/tests/04-cqfd_init_context
@@ -41,3 +41,10 @@ fi
 ################################################################################
 cp -f cqfdrc-test .cqfdrc
 mv -f .cqfd/docker/Dockerfile.orig .cqfd/docker/Dockerfile
+
+################################################################################
+# restore container
+################################################################################
+if ! "$cqfd" init; then
+	jtest_log error "restore container failed"
+fi
diff --git a/tests/11-cqfd_multi_platform b/tests/11-cqfd_multi_platform
--- a/tests/11-cqfd_multi_platform
+++ b/tests/11-cqfd_multi_platform
@@ -79,3 +79,8 @@ rm -f linux-arm64-cqfd
 # restore .cqfdrc and Dockerfile
 mv -f .cqfdrc.orig .cqfdrc
 mv -f .cqfd/docker/Dockerfile.orig .cqfd/docker/Dockerfile
+
+# restore container
+if ! "$cqfd" init; then
+	jtest_log error "restore container failed"
+fi
