tests: 05-cqfd_init_image: test and log command errors
This tests and logs command errors.

diff --git a/tests/05-cqfd_init_image b/tests/05-cqfd_init_image
--- a/tests/05-cqfd_init_image
+++ b/tests/05-cqfd_init_image
@@ -19,7 +19,9 @@ cp -f cqfdrc-image .cqfdrc
 image="ubuntu:16.04"
 if "${cqfd_docker[@]}" inspect "$image" &>/dev/null; then
 	jtest_log info "${cqfd_docker[-1]} registry contains image named: $image, removing..."
-	"${cqfd_docker[@]}" rmi "$image"
+	if ! "${cqfd_docker[@]}" rmi "$image"; then
+		jtest_log error "removing image failed"
+	fi
 fi
 
 jtest_prepare "run cqfd init should pull image $image from remote registry"
