cqfd: add CQFD_WORKDIR environment
This adds the environment CQFD_WORKDIR to set the path to the .cqfdrc
file. The path is either relative a absolute.

diff --git a/tests/05-cqfd_run_alt_ext b/tests/05-cqfd_run_alt_ext
--- a/tests/05-cqfd_run_alt_ext
+++ b/tests/05-cqfd_run_alt_ext
@@ -22,7 +22,7 @@ cd "$workdir" || exit 1
 ################################################################################
 # 'cqfd run' using nonexistent working directory should fail
 ################################################################################
-jtest_prepare "cqfd run using inexistant working directory should fail"
+jtest_prepare "cqfd run using inexistant working directory set using -w should fail"
 if ! "$cqfd" -w "nonexistentdir" run; then
 	jtest_result pass
 else
@@ -42,11 +42,43 @@ fi
 ################################################################################
 # 'cqfd run' using alternate working directory should work
 ################################################################################
-jtest_prepare "cqfd run using working directory should work"
+jtest_prepare "cqfd run using working directory set using -w should work"
 if "$cqfd" -w ".." run "stat -c '%u' .." | grep -q "$UID"; then
 	jtest_result pass
 else
 	jtest_result fail
+fi
+
+################################################################################
+# 'cqfd run' using nonexistent working directory should fail
+################################################################################
+jtest_prepare "cqfd run using inexistant working directory set using CQFD_WORKDIR should fail"
+if ! CQFD_WORKDIR="nonexistentdir" "$cqfd" run; then
+	jtest_result pass
+else
+	jtest_result fail
+fi
+
+################################################################################
+# 'cqfd run' using alternate working directory should work
+################################################################################
+jtest_prepare "cqfd run using working directory set using CQFD_WORKDIR should work"
+if CQFD_WORKDIR=".." "$cqfd" run "stat -c '%u' .." | grep -q "$UID"; then
+	jtest_result pass
+else
+	jtest_result fail
+
+fi
+
+################################################################################
+# 'cqfd run' using alternate working directory should work
+################################################################################
+jtest_prepare "cqfd run using working directory set using CQFD_WORKDIR should work"
+if CQFD_WORKDIR="$PWD/.." "$cqfd" run "stat -c '%u' .." | grep -q "$UID"; then
+	jtest_result pass
+else
+	jtest_result fail
+
 fi
 
 ################################################################################
