tests: 05-cqfd_init_flavor: remove duplicated test
This removes duplicated test.

diff --git a/tests/05-cqfd_init_flavor b/tests/05-cqfd_init_flavor
--- a/tests/05-cqfd_init_flavor
+++ b/tests/05-cqfd_init_flavor
@@ -28,13 +28,10 @@ else
 	jtest_result fail
 fi
 
-jtest_prepare "run cqfd init without build flavor should pass"
-if cqfd init && \
-   cqfd | grep "^NAME=\"Ubuntu\"$"; then
-	jtest_result pass
-else
-	jtest_result fail
-fi
-
 # restore initial .cqfdrc
 mv -f .cqfdrc.orig .cqfdrc
+
+# restore container
+if ! cqfd init; then
+	jtest_log error "restore container failed"
+fi
