tests: 05-cqfd_run_c: flatten functions
This flattens the functions.

diff --git a/tests/05-cqfd_run_c b/tests/05-cqfd_run_c
--- a/tests/05-cqfd_run_c
+++ b/tests/05-cqfd_run_c
@@ -8,65 +8,49 @@ test_run_c_file="test_run_c.txt"
 
 cd "$TDIR/" || exit 1
 
-test_setup() {
-	if [ -f "$test_file" ] || [ -f "$test_run_c_file" ]; then
-		jtest_log info "$test_file or $test_run_c_file already present before test, removing..."
-		rm -f "$test_file"
-		rm -f "$test_run_c_file"
-	fi
-}
-
-test_cleanup() {
+if [ -f "$test_file" ] || [ -f "$test_run_c_file" ]; then
+	jtest_log info "$test_file or $test_run_c_file already present before test, removing..."
 	rm -f "$test_file"
 	rm -f "$test_run_c_file"
-}
+fi
 
 # Append default command build with an additional option
-test_step1() {
-	jtest_prepare "running \"cqfd run -c\" makes it run with appended arguments"
-	if ! cqfd run -c --debug >>"$test_run_c_file"; then
-		jtest_log fatal "cqfd run -c failed"
-		jtest_result fail
-		rm -f "$test_run_c_file"
-		return
-	fi
+jtest_prepare "running \"cqfd run -c\" makes it run with appended arguments"
+if ! cqfd run -c --debug >>"$test_run_c_file"; then
+	jtest_log fatal "cqfd run -c failed"
+	jtest_result fail
+	rm -f "$test_run_c_file"
+fi
 
-	# at the end of this test, $test_run_c_file is populated
-	if ! grep "^Successfully remade target file 'build'\.$" "$test_run_c_file"; then
-		jtest_log fatal "$test_run_c_file not present after test"
-		jtest_result fail
-		rm -f "$test_run_c_file"
-		return
-	fi
+# at the end of this test, $test_run_c_file is populated
+if ! grep "^Successfully remade target file 'build'\.$" "$test_run_c_file"; then
+	jtest_log fatal "$test_run_c_file not present after test"
+	jtest_result fail
+	rm -f "$test_run_c_file"
+fi
 
-	# at the end of either test, $test_file is populated
-	if grep "^cqfd$" "$test_file"; then
-		jtest_result pass
-	else
-		jtest_log fatal "$test_file not present after test"
-		jtest_result fail
-		rm -f "$test_file"
-		return
-	fi
+# at the end of either test, $test_file is populated
+if grep "^cqfd$" "$test_file"; then
+	jtest_result pass
+else
+	jtest_log fatal "$test_file not present after test"
+	jtest_result fail
+	rm -f "$test_file"
+fi
 
-	# cleanup
-	make clean
-}
+# cleanup
+make clean
+
+rm -f "$test_file"
+rm -f "$test_run_c_file"
 
 # Build the default command with run -c
-test_step2() {
-	jtest_prepare "running \"cqfd run -c\" with no argument makes it fail"
-	if ! cqfd run -c; then
-		jtest_result pass
-	else
-		jtest_result fail
-	fi
-}
+jtest_prepare "running \"cqfd run -c\" with no argument makes it fail"
+if ! cqfd run -c; then
+	jtest_result pass
+else
+	jtest_result fail
+fi
 
-test_setup
-test_step1
-test_cleanup
-
-test_setup
-test_step2
-test_cleanup
+rm -f "$test_file"
+rm -f "$test_run_c_file"
