tests: test every cqfd commands
This tests every single cqfd commands in the tests.

diff --git a/tests/05-cqfd_run_dockerfile b/tests/05-cqfd_run_dockerfile
--- a/tests/05-cqfd_run_dockerfile
+++ b/tests/05-cqfd_run_dockerfile
@@ -22,4 +22,7 @@ fi
 
 # restore Dockerfile
 mv -f .cqfd/docker/Dockerfile.orig .cqfd/docker/Dockerfile
-"$cqfd" init
+jtest_log info "restore container"
+if ! "$cqfd" init; then
+	jtest_log fatal "cqfd init failed"
+fi
diff --git a/tests/05-cqfd_run_su_or_sudo_backend b/tests/05-cqfd_run_su_or_sudo_backend
--- a/tests/05-cqfd_run_su_or_sudo_backend
+++ b/tests/05-cqfd_run_su_or_sudo_backend
@@ -76,4 +76,7 @@ fi
 # Restore initial Dockerfile.
 ################################################################################
 mv -f .cqfd/docker/Dockerfile.orig .cqfd/docker/Dockerfile
-"$cqfd" init
+jtest_log info "restore container"
+if ! "$cqfd" init; then
+	jtest_log fatal "cqfd init failed"
+fi
