tests: test every cqfd commands
This tests every single cqfd commands in the tests.

diff --git a/tests/05-cqfd_run_check_dependencies b/tests/05-cqfd_run_check_dependencies
--- a/tests/05-cqfd_run_check_dependencies
+++ b/tests/05-cqfd_run_check_dependencies
@@ -70,4 +70,7 @@ fi
 # restore initial Dockerfile
 ################################################################################
 mv -f .cqfd/docker/Dockerfile.orig .cqfd/docker/Dockerfile
-"$cqfd" init
+jtest_log info "restore container"
+if ! "$cqfd" init; then
+	jtest_log error "cqfd init failed"
+fi
