tests: test every cqfd commands
This tests every single cqfd commands in the tests.

diff --git a/tests/05-cqfd_run_c_flavor b/tests/05-cqfd_run_c_flavor
--- a/tests/05-cqfd_run_c_flavor
+++ b/tests/05-cqfd_run_c_flavor
@@ -20,7 +20,10 @@ if [ -f "$test_file" ] || [ -f "$test_run_c_file" ]; then
 fi
 
 jtest_prepare "build cmd for '$flavor' flavor and concatenate with an additional option"
-"$cqfd" -b "$flavor" run -c --debug >>"$test_run_c_file"
+if ! "$cqfd" -b "$flavor" run -c --debug >>"$test_run_c_file"; then
+	jtest_log fatal "cqfd run -c --debug failed"
+	fail=1
+fi
 
 # at the end of this test, $test_run_c_file is populated
 if ! grep -qw "target 'foo'" "$test_run_c_file"; then
