tests: 05-cqfd_init_{extra_env,image,tag}: restore container at teardown
This restores the container after the end of tests.

diff --git a/tests/05-cqfd_init_extra_env b/tests/05-cqfd_init_extra_env
--- a/tests/05-cqfd_init_extra_env
+++ b/tests/05-cqfd_init_extra_env
@@ -37,3 +37,10 @@ fi
 # restore initial Dockerfile
 ################################################################################
 mv -f .cqfd/docker/Dockerfile.orig .cqfd/docker/Dockerfile
+
+################################################################################
+# restore container
+################################################################################
+if ! cqfd init; then
+	jtest_log error "restore container failed"
+fi
diff --git a/tests/05-cqfd_init_image b/tests/05-cqfd_init_image
--- a/tests/05-cqfd_init_image
+++ b/tests/05-cqfd_init_image
@@ -61,3 +61,10 @@ fi
 ################################################################################
 mv -f .cqfdrc.orig .cqfdrc
 mv -f .cqfd/docker/Dockerfile.orig .cqfd/docker/Dockerfile
+
+################################################################################
+# restore container
+################################################################################
+if ! cqfd init; then
+	jtest_log error "restore container failed"
+fi
