*** :{) ***

diff --git a/tests/05-cqfd_run_c_flavor b/tests/05-cqfd_run_c_flavor
--- a/tests/05-cqfd_run_c_flavor
+++ b/tests/05-cqfd_run_c_flavor
@@ -18,12 +18,15 @@ if [ -f "$test_file" ] || [ -f "$test_run_c_file" ]; then
 fi
 
 jtest_prepare "build cmd for '$flavor' flavor and concatenate with an additional option"
-if ! "$cqfd" -b "$flavor" run -c --debug >>"$test_run_c_file"; then
-	jtest_log fatal "cqfd run -c --debug failed"
-	fail=1
-fi
+echo 1
+"$cqfd" -b "$flavor" run -c --debug >>"$test_run_c_file"
+#if ! "$cqfd" -b "$flavor" run -c --debug >>"$test_run_c_file"; then
+#	jtest_log fatal "cqfd run -c --debug failed"
+#	fail=1
+#fi
 
 # at the end of this test, $test_run_c_file is populated
+echo 2
 if ! grep -qw "target 'foo'" "$test_run_c_file"; then
 	jtest_log fatal "$test_run_c_file not present after test"
 	fail=1
@@ -31,12 +34,14 @@ if ! grep -qw "target 'foo'" "$test_run_c_file"; then
 fi
 
 # at the end of either test, $test_file is populated
+echo 3
 if ! grep -qw "cqfd" "$test_file"; then
 	jtest_log fatal "$test_file not present after test"
 	fail=1
 	rm -f "$test_file"
 fi
 
+echo 4
 if [ "$fail" -eq 0 ]; then
 	jtest_result pass
 else
