tests: 05-cqfd_run_flavor: flatten loop
This flattens the for loop.

diff --git a/tests/05-cqfd_run_flavor b/tests/05-cqfd_run_flavor
--- a/tests/05-cqfd_run_flavor
+++ b/tests/05-cqfd_run_flavor
@@ -8,30 +8,32 @@ flavor="foo"
 cd "$TDIR/" || exit 1
 
 # First pass: build a simple flavor
+test_file=$flavor
+jtest_prepare "cqfd build cmd for '$flavor' flavor"
+cqfd -b "$flavor"
+
+# shellcheck disable=SC2181
+if [ "$?" -eq 0 ] && [ -f "$test_file" ]; then
+	jtest_result pass
+else
+	jtest_log fatal "failed or test file not present after execution"
+	jtest_result fail
+fi
+rm -f "$test_file"
+
 # Second pass: override flavor build with an additional command
+test_file=$flavor
+jtest_prepare "cqfd run build cmd for '$flavor' flavor"
+cqfd -b "$flavor" run
 
-for i in 0 1; do
-	jtest_log info "run cqfd with a given '$flavor' flavor, pass $i"
-
-	if [ "$i" = "0" ]; then
-		test_file=$flavor
-		jtest_prepare "cqfd build cmd for '$flavor' flavor"
-		cqfd -b "$flavor"
-	else
-		test_file=$flavor
-		jtest_prepare "cqfd run build cmd for '$flavor' flavor"
-		cqfd -b "$flavor" run
-	fi
-
-	# shellcheck disable=SC2181
-	if [ "$?" -eq 0 ] && [ -f "$test_file" ]; then
-		jtest_result pass
-	else
-		jtest_log fatal "failed or test file not present after execution"
-		jtest_result fail
-	fi
-	rm -f "$test_file"
-done
+# shellcheck disable=SC2181
+if [ "$?" -eq 0 ] && [ -f "$test_file" ]; then
+	jtest_result pass
+else
+	jtest_log fatal "failed or test file not present after execution"
+	jtest_result fail
+fi
+rm -f "$test_file"
 
 # cleanup
 make clean
