tests: 06-cqfd_release: create tmp directories in TDIR
mktemp -d creates a directory to /tmp/tmp.XXXXXX if TEMPLATE is not
given and if TMPDIR is unset.

The tests are run in a mktemp directory already[1][2], and that
directory is removed at the end of tests[3] (if the tests are not
interrupted[3]). The directory is pointed by "$TDIR".

Thus, additionnal temporary files and directories can be created in that
directory to avoid having multiple places to clean up during a test or
after the tests. It polutes even more the temporary directory of the
system if files and directories are left uncleaned.

This removes the use of mktemp -d to create directories directly in the
existing temporary directory "$TDIR" to avoid poluting the temporary
directory of the system if the tests are interrupted.

[1]: https://github.com/savoirfairelinux/cqfd/blob/v5.7.0/tests/Makefile#L14
[2]: https://github.com/savoirfairelinux/cqfd/blob/v5.7.0/tests/Makefile#L17
[3]: https://github.com/savoirfairelinux/cqfd/blob/v5.7.0/tests/Makefile#L29-L31

diff --git a/tests/06-cqfd_release b/tests/06-cqfd_release
--- a/tests/06-cqfd_release
+++ b/tests/06-cqfd_release
@@ -107,12 +107,12 @@ if ! "$cqfd" release; then
 	jtest_log fatal "cqfd release failed"
 	result="fail"
 fi
-tmp_dir=$(mktemp -d)
-if ! tar xf cqfd-test.tar.xz -C "$tmp_dir"; then
+mkdir "$TDIR/output"
+if ! tar xf cqfd-test.tar.xz -C "$TDIR/output"; then
 	jtest_log fatal "tar failed"
 	result="fail"
 fi
-if [ -L "$tmp_dir"/link.txt ] || ! diff "$tmp_dir"/a/cqfd_a.txt "$tmp_dir"/link.txt; then
+if [ -L "$TDIR/output/link.txt" ] || ! diff "$TDIR/output/a/cqfd_a.txt" "$TDIR/output/link.txt"; then
 	jtest_log fatal "link.txt is not a symlink or differs from cqfd_a.txt"
 	result="fail"
 fi
@@ -124,8 +124,9 @@ sed -i '/tar_options=/d' .cqfdrc
 sed -i '/files=/d' .cqfdrc
 echo "files=\"$rel_files\"" >>.cqfdrc
 
+# cleanup
 rm -f cqfd-test.tar.xz
-rm -rf "$tmp_dir"
+rm -rf "$TDIR/output"
 
 ################################################################################
 # Now test adding an archive filename template to the config
